### ISSUE TITLE
Compilation fails on OS 10.9.5

### ISSUE THREAD

**Issue by mrsmn** [matthewelse/pyxpcconnection#1]
Hi there,

compilation fails with boost `1.60.0` (OS 10.9.5, Xcode 6.2):

```
https://paste.calypso.pm/Wl27OBQg
```

My C skills aren't good enough for me to fix this.

Cheers.

**Comment by matthewelse** [comment]
Hi @mrsmn I'll try and have a look at this for you

**Comment by jcushman** [comment]
Not sure if it's the same issue, but I had to run `brew install boost-python` to get compilation to work.
